const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const js=fs.readFileSync(path.join(root,'assets/reviews.js'),'utf8');
const samples=vm.runInNewContext(js.match(/const samples = (\[[\s\S]*?\]);/)[1]);
assert.equal(samples.length,6);
assert.deepEqual([...new Set(samples.map(r=>r.rating))].sort(),[3,4,5]);
assert(samples.every(r=>/^[A-Za-z ]+$/.test(r.name)));
for(const id of ['reviews','sampleReviews','reviewForm','reviewName','reviewRating','reviewText','reviewStatus','sendReview','reviewDrafts','shopMap'])assert(html.includes(`id="${id}"`));
assert(html.includes('fictional examples') && html.includes('not customer testimonials or Google reviews'));
assert(html.includes('not the exact shop pin'));
assert(!html.includes('mZ4QWN1HgJYKVyG36') && !html.includes('103359021812915362606'));
assert(html.includes('www.google.com/maps/embed?pb=') && html.includes('height:260px'));
assert(html.includes('loading="lazy"') && html.includes('assets/reviews.js'));
assert(js.includes("text.textContent = review.text") && js.includes('Draft saved only in this browser'));
assert(js.includes('mailto:polwaththahardware2024@gmail.com'));
const logo=fs.readFileSync(path.join(root,'assets/brand/polwaththa-logo-2024.webp'));
assert.equal(logo.toString('ascii',8,12),'WEBP');assert(logo.length<50000);
console.log('PASS: new logo, six labelled samples with 3/4/5 stars, private drafts/email form, lazy area map; no personal live-location link exposed.');
